### ISSUE TITLE
update GNOME runtime to 3.38

### ISSUE THREAD

**Issue by eszlari** [flathub/org.glimpse_editor.Glimpse#4]

**Comment by ghost** [comment]
To update on progress with this:
- We have already updated GNOME platform version from 3.36 to 3.38 and tested in the `dev-g210` branch here: https://github.com/glimpse-editor/Glimpse/commit/714d2310817aedea78d542636fba6bf923bab5be
- I have now applied the same changes on the beta channel here: https://github.com/flathub/org.glimpse_editor.Glimpse/commit/87b4d7abedcdf6c4311d2a613839b2a321785c16

Once builtbot has completed, the end result will need to be tested. (We don't just rely on automated sanity checks, we run the application and make sure it functions correctly). Link: https://flathub.org/builds/#/builders/32/builds/30018

If everything checks out, then we will make the same changes on the main channel that everyone uses (built from `master` branch. I'd like to change it to `main`, but apparently that will confuse buildbot: https://github.com/flathub/flathub/issues/1593)

**Comment by ghost** [comment]
First beta build failed. New link: https://flathub.org/builds/#/builders/32/builds/30021

Apparently I'd forgotten to remove the webkit component we don't use: https://github.com/flathub/org.glimpse_editor.Glimpse/commit/7e4e4bc20bee1765b61c738bd6f96ebe1e87707f

**Comment by ghost** [comment]
Okay, an updated release of Glimpse Image Editor 0.2.0 is now available in the beta channel with GNOME platform version 3.38. You can test it by following the instructions here: https://github.com/glimpse-editor/Glimpse/wiki/Beta-Testing-with-Flathub-%28Linux%29

Once we have verified it works properly on a few different Linux distributions, we will start the process of publishing it in the stable channel.

**IMPORTANT**: This change does not just involve changing platform version in the manifest file from 3.36 to 3.38! We also have to remove an unneeded webkit component and update the versions for a range of dependencies, otherwise the flatpak will fail to build or the application will crash.

**Comment by ghost** [comment]
So far so good with my own testing, although I'll wait for others on project Matrix channel to verify.

Provisionally pushing changes to `master` here: https://github.com/flathub/org.glimpse_editor.Glimpse/commit/cd50b8421b2719438aa2b0518a15b1254a16c5a0
Buildbot link: https://flathub.org/builds/#/builders/32/builds/30040

**Comment by ghost** [comment]
Publishing via this link: https://flathub.org/builds/#/builders/29/builds/19319

**Comment by ghost** [comment]
Okay, the fix should now be delivered. Run `flatpak update` if you still see GNOME Platform 3.36 as a required dependency.
